# Import library and read file

In [51]:
import pandas as pd

In [84]:
df = pd.read_csv('NORS_raw.csv')

/var/folders/3p/cnl_cpmx6jn3271cnct3f68c0000gn/T/ipykernel_20736/2767054102.py:1: DtypeWarning: Columns (0: Illnesses, 1: Info On Hospitalizations, 2: Info On Deaths) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('NORS_raw.csv')

In [53]:
df.head()

,Year,Month,State,Primary Mode,Etiology,Serotype or Genotype,Etiology Status,Setting,Illnesses,Hospitalizations,Info On Hospitalizations,Deaths,Info On Deaths,Food Vehicle,Food Contaminated Ingredient,IFSAC Category,Water Exposure,Water Type,Animal Type
0,1971,2,California,Water,Copper,NaN,Confirmed,Restaurant,2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN
1,1971,6,Alabama,Water,Selenium,NaN,Confirmed,Unknown,3,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Drinking water,Individual/Private,NaN
2,1971,6,Arkansas,Water,Hepatitis A,NaN,Confirmed,Store,98,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN
3,1971,6,Missouri,Water,Unknown,NaN,Suspected,Subdivision/Neighborhood,2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN
4,1971,6,Oregon,Water,Unknown,NaN,Suspected,Restaurant,200,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN

In [54]:
df.shape

(66713, 19)

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 66713 entries, 0 to 66712
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Year                          66713 non-null  int64
 1   Month                         66713 non-null  int64
 2   State                         66713 non-null  str
 3   Primary Mode                  66713 non-null  str
 4   Etiology                      50375 non-null  str
 5   Serotype or Genotype          16470 non-null  str
 6   Etiology Status               50375 non-null  str
 7   Setting                       60804 non-null  str
 8   Illnesses                     66713 non-null  object
 9   Hospitalizations              58155 non-null  float64
 10  Info On Hospitalizations      58480 non-null  object
 11  Deaths                        58785 non-null  float64
 12  Info On Deaths                58463 non-null  object
 13  Food Vehicle                  12446 non-null  str
 14  Food Contaminated Ingredient  2750 non-null   str
 15  IFSAC Category                11705 non-null  str
 16  Water Exposure                3106 non-null   str
 17  Water Type                    2730 non-null   str
 18  Animal Type                   587 non-null    str
dtypes: float64(2), int64(2), object(3), str(12)
memory usage: 14.9+ MB

# Modifying Column Types

In [56]:
df["Illnesses"].map(type).value_counts()

Illnesses
<class 'str'>    65536
<class 'int'>     1177
Name: count, dtype: int64

In [57]:
df["Info On Hospitalizations"].map(type).value_counts()

Info On Hospitalizations
<class 'str'>      57315
<class 'float'>     9398
Name: count, dtype: int64

In [58]:
df["Info On Deaths"].map(type).value_counts()

Info On Deaths
<class 'str'>      57296
<class 'float'>     9417
Name: count, dtype: int64

In [59]:
df["Illnesses"] = df["Illnesses"].astype(str).str.replace(",", "")
df["Illnesses"] = df["Illnesses"].astype(int)

In [60]:
df["Info On Hospitalizations"] = df["Info On Hospitalizations"].astype(str).str.replace(",", "")
df["Info On Hospitalizations"] = df["Info On Hospitalizations"].astype(float)

In [61]:
df["Info On Deaths"] = df["Info On Deaths"].astype(str).str.replace(",", "")
df["Info On Deaths"] = df["Info On Deaths"].astype(float)

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 66713 entries, 0 to 66712
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Year                          66713 non-null  int64
 1   Month                         66713 non-null  int64
 2   State                         66713 non-null  str
 3   Primary Mode                  66713 non-null  str
 4   Etiology                      50375 non-null  str
 5   Serotype or Genotype          16470 non-null  str
 6   Etiology Status               50375 non-null  str
 7   Setting                       60804 non-null  str
 8   Illnesses                     66713 non-null  int64
 9   Hospitalizations              58155 non-null  float64
 10  Info On Hospitalizations      58480 non-null  float64
 11  Deaths                        58785 non-null  float64
 12  Info On Deaths                58463 non-null  float64
 13  Food Vehicle                  12446 non-null  str
 14  Food Contaminated Ingredient  2750 non-null   str
 15  IFSAC Category                11705 non-null  str
 16  Water Exposure                3106 non-null   str
 17  Water Type                    2730 non-null   str
 18  Animal Type                   587 non-null    str
dtypes: float64(4), int64(3), str(12)
memory usage: 14.9 MB

# Dealing with Duplicates

In [63]:
df.duplicated().sum()

np.int64(1428)

In [64]:
df[df.duplicated(keep=False)]

,Year,Month,State,Primary Mode,Etiology,Serotype or Genotype,Etiology Status,Setting,Illnesses,Hospitalizations,Info On Hospitalizations,Deaths,Info On Deaths,Food Vehicle,Food Contaminated Ingredient,IFSAC Category,Water Exposure,Water Type,Animal Type
516,1983,7,Minnesota,Water,Norovirus unknown,NaN,Confirmed,Park - Community/Municipal,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recreational water -- untreated,Unknown,NaN
517,1983,7,Minnesota,Water,Norovirus unknown,NaN,Confirmed,Park - Community/Municipal,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recreational water -- untreated,Unknown,NaN
1056,1998,1,Florida,Food,NaN,NaN,NaN,Restaurant: Other,2,0.0,2.0,0.0,2.0,"steak, unspecified",NaN,Beef,NaN,NaN,NaN
1060,1998,1,Florida,Food,NaN,NaN,NaN,Restaurant: Other,2,0.0,2.0,0.0,2.0,"steak, unspecified",NaN,Beef,NaN,NaN,NaN
1070,1998,1,Ohio,Food,NaN,NaN,NaN,Restaurant: Other,2,0.0,2.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66620,2023,12,Minnesota,Person-to-person,Norovirus unknown,NaN,Suspected,Child daycare/preschool,7,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
66634,2023,12,Iowa,Indeterminate/unknown,NaN,NaN,NaN,Restaurant,3,0.0,3.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
66635,2023,12,Iowa,Indeterminate/unknown,NaN,NaN,NaN,Restaurant,3,0.0,3.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
66706,2023,12,Wisconsin,Person-to-person,Norovirus unknown,NaN,Suspected,Long-term care/nursing home/assisted living fa...,20,1.0,20.0,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN
66712,2023,12,Wisconsin,Person-to-person,Norovirus unknown,NaN,Suspected,Long-term care/nursing home/assisted living fa...,20,1.0,20.0,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
df = df.drop_duplicates()

In [66]:
df.duplicated().sum()

np.int64(0)

# Cleaning

In [67]:
#Filter to non-null etiology
df_clean = df[df['Etiology'].notna()].copy()

In [68]:
df_clean.Etiology.isna().sum()

np.int64(0)

In [69]:
#Filter to single-etiology outbreaks
df_clean['etiology_list'] = df_clean['Etiology'].str.split(';')
df_clean['etiology_status_list'] = df_clean['Etiology Status'].str.split(';')

In [70]:
df_clean = df_clean[(df_clean['etiology_list'].str.len() == 1) & (df_clean['etiology_status_list'].str.len() == 1) & (df_clean['etiology_status_list'].str[0] == 'Confirmed')].copy()

In [71]:
df_clean

,Year,Month,State,Primary Mode,Etiology,Serotype or Genotype,Etiology Status,Setting,Illnesses,Hospitalizations,...,Deaths,Info On Deaths,Food Vehicle,Food Contaminated Ingredient,IFSAC Category,Water Exposure,Water Type,Animal Type,etiology_list,etiology_status_list
0,1971,2,California,Water,Copper,NaN,Confirmed,Restaurant,2,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN,[Copper],[Confirmed]
1,1971,6,Alabama,Water,Selenium,NaN,Confirmed,Unknown,3,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Individual/Private,NaN,[Selenium],[Confirmed]
2,1971,6,Arkansas,Water,Hepatitis A,NaN,Confirmed,Store,98,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN,[Hepatitis A],[Confirmed]
8,1971,7,Mississippi,Water,Shigella sonnei,NaN,Confirmed,Camp/cabin,187,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN,[Shigella sonnei],[Confirmed]
9,1971,7,New Jersey,Water,Hepatitis A,NaN,Confirmed,Camp/cabin,22,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN,[Hepatitis A],[Confirmed]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66700,2023,12,Multistate,Environmental contamination other than food/water,"Escherichia coli, Shiga toxin-producing",O157:H7,Confirmed,NaN,5,3.0,...,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,"[Escherichia coli, Shiga toxin-producing]",[Confirmed]
66701,2023,12,Illinois,Person-to-person,Norovirus unknown,NaN,Confirmed,Long-term care/nursing home/assisted living fa...,36,1.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[Norovirus unknown],[Confirmed]
66702,2023,12,South Dakota,Indeterminate/unknown,Salmonella enterica,Litchfield,Confirmed,Long-term care/nursing home/assisted living fa...,3,1.0,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,[Salmonella enterica],[Confirmed]
66703,2023,12,Arizona,Food,Salmonella enterica,Javiana,Confirmed,NaN,3,1.0,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,[Salmonella enterica],[Confirmed]
66704,2023,12,Multistate,Food,Listeria monocytogenes,NaN,Confirmed,Hospital;Unknown,9,6.0,...,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,[Listeria monocytogenes],[Confirmed]

In [72]:
#Convert the single-item list back to a string
df_clean['Etiology'] = df_clean['etiology_list'].str[0]

In [73]:
def consolidate_etiology(x):
    if pd.isna(x):
        return x
    if 'Norovirus' in x:
        return 'Norovirus'
    if 'Escherichia coli' in x:
        return 'STEC'
    if 'Salmonella' in x:
        return 'Salmonella'
    if 'Campylobacter' in x:
        return 'Campylobacter'
    if 'Shigella' in x:
        return 'Shigella'
    if 'Clostridium' in x:
        return 'Clostridium'
    if 'Cryptosporidium' in x:
            return 'Cryptosporidium'
    return x

df_clean['Etiology_clean'] = df_clean['Etiology'].apply(consolidate_etiology)

In [74]:
top_n = df_clean['Etiology_clean'].value_counts().nlargest(10).index
df_clean['Etiology_top'] = df_clean['Etiology_clean'].where(
    df_clean['Etiology_clean'].isin(top_n), 'Other'
)

In [75]:
df_clean['Etiology_top'].value_counts()

Etiology_top
Norovirus                 13031
Salmonella                 3855
Other                      2123
Shigella                   1171
STEC                       1127
Legionella pneumophila      726
Campylobacter               688
Clostridium                 648
Cryptosporidium             629
Scombroid toxin             423
Ciguatoxin                  341
Name: count, dtype: int64

In [76]:
df_clean = df_clean.drop(columns=['etiology_list', 'etiology_status_list'])

In [77]:
df_clean

,Year,Month,State,Primary Mode,Etiology,Serotype or Genotype,Etiology Status,Setting,Illnesses,Hospitalizations,...,Deaths,Info On Deaths,Food Vehicle,Food Contaminated Ingredient,IFSAC Category,Water Exposure,Water Type,Animal Type,Etiology_clean,Etiology_top
0,1971,2,California,Water,Copper,NaN,Confirmed,Restaurant,2,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN,Copper,Other
1,1971,6,Alabama,Water,Selenium,NaN,Confirmed,Unknown,3,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Individual/Private,NaN,Selenium,Other
2,1971,6,Arkansas,Water,Hepatitis A,NaN,Confirmed,Store,98,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN,Hepatitis A,Other
8,1971,7,Mississippi,Water,Shigella sonnei,NaN,Confirmed,Camp/cabin,187,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Community,NaN,Shigella,Shigella
9,1971,7,New Jersey,Water,Hepatitis A,NaN,Confirmed,Camp/cabin,22,NaN,...,0.0,NaN,NaN,NaN,NaN,Drinking water,Other,NaN,Hepatitis A,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66700,2023,12,Multistate,Environmental contamination other than food/water,"Escherichia coli, Shiga toxin-producing",O157:H7,Confirmed,NaN,5,3.0,...,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,STEC,STEC
66701,2023,12,Illinois,Person-to-person,Norovirus unknown,NaN,Confirmed,Long-term care/nursing home/assisted living fa...,36,1.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Norovirus,Norovirus
66702,2023,12,South Dakota,Indeterminate/unknown,Salmonella enterica,Litchfield,Confirmed,Long-term care/nursing home/assisted living fa...,3,1.0,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Salmonella,Salmonella
66703,2023,12,Arizona,Food,Salmonella enterica,Javiana,Confirmed,NaN,3,1.0,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Salmonella,Salmonella
66704,2023,12,Multistate,Food,Listeria monocytogenes,NaN,Confirmed,Hospital;Unknown,9,6.0,...,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,Listeria monocytogenes,Other

In [78]:
df_clean["Primary Mode"] = df_clean["Primary Mode"].replace(
    "Environmental contamination other than food/water",
    "Environmental"
)

In [79]:
def group_setting(x):
    if pd.isna(x):
        return 'Unknown'
    elif x == 'Long-term care/nursing home/assisted living facility':
        return 'Long-term care'
    elif x == 'Private home/residence':
        return 'Private residence'
    elif x.startswith('Restaurant') or x in ['Caterer', 'Banquet Facility (food prepared and served on-site)']:
        return 'Restaurant'
    elif x in ['School/college/university', 'Child daycare/preschool']:
        return 'School'
    elif x == 'Hospital':
        return 'Hospital'
    elif x == 'Hotel/motel':
        return 'Hotel'
    elif x in ['Community/municipality', 'Religious facility']:
        return 'Community'
    elif x == 'Grocery store/bakery/deli/convenience store':
        return 'Grocery'
    elif x == 'Unknown':
        return 'Unknown'
    else:
        return 'Other'

In [80]:
df_clean['Setting_group'] = df_clean['Setting'].apply(group_setting)
df_clean['Setting_group'].value_counts()

Setting_group
Long-term care       7134
Restaurant           5844
Other                3931
Unknown              2335
Private residence    1967
School               1899
Hospital              679
Community             416
Hotel                 393
Grocery               164
Name: count, dtype: int64

In [81]:
df_clean = df_clean.reset_index(drop=True)

In [82]:
df_clean.to_csv("NORS_cleaned.csv", index=False)